"""
Generic Banking API for MyBank

Basic RESTful API endpoints for banking operations.
Generated by Code Agent
"""
from datetime import datetime
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from typing import List, Dict, Any

app = FastAPI(title="MyBank API", version="1.0.0")


class StatusResponse(BaseModel):
    """API status response."""
    status: str
    timestamp: datetime
    version: str


@app.get("/api/v1/status", response_model=StatusResponse)
async def get_status():
    """Get API status."""
    return StatusResponse(
        status="operational",
        timestamp=datetime.now(),
        version="1.0.0"
    )


@app.get("/api/v1/health")
async def health_check():
    """Health check endpoint."""
    return {"status": "healthy", "timestamp": datetime.now()}
