"""
Credit Card Management System for MyBank

Comprehensive credit card platform with lifecycle management, transaction processing,
and integrated fraud protection.
Generated by LangGraph Complete Workflow for Credit Card Platform
"""
from dataclasses import dataclass, field
from typing import Dict, List, Any, Optional, Literal
from datetime import datetime, date
from decimal import Decimal
from enum import Enum
import uuid
import json


class CardStatus(Enum):
    """Credit card status enumeration."""
    PENDING = "pending"
    ACTIVE = "active"
    SUSPENDED = "suspended"
    BLOCKED = "blocked"
    EXPIRED = "expired"
    CLOSED = "closed"


class TransactionType(Enum):
    """Transaction type enumeration."""
    PURCHASE = "purchase"
    CASH_ADVANCE = "cash_advance"
    BALANCE_TRANSFER = "balance_transfer"
    PAYMENT = "payment"
    FEE = "fee"
    INTEREST = "interest"
    REWARD = "reward"
    REFUND = "refund"


class TransactionStatus(Enum):
    """Transaction processing status."""
    PENDING = "pending"
    AUTHORIZED = "authorized"
    CAPTURED = "captured"
    DECLINED = "declined"
    REVERSED = "reversed"
    SETTLED = "settled"


@dataclass
class Customer:
    """Customer data model."""
    customer_id: str
    first_name: str
    last_name: str
    email: str
    phone: str
    address: Dict[str, str]
    ssn_hash: str  # Hashed SSN for privacy
    date_of_birth: date
    credit_score: Optional[int] = None
    annual_income: Optional[Decimal] = None
    employment_status: Optional[str] = None
    created_at: datetime = field(default_factory=datetime.now)


@dataclass
class CreditCard:
    """Credit card data model."""
    card_id: str
    customer_id: str
    card_number_token: str  # Tokenized card number
    card_type: str  # Visa, Mastercard, Amex
    product_name: str  # Rewards Card, Premium Card, etc.
    credit_limit: Decimal
    available_credit: Decimal
    current_balance: Decimal
    minimum_payment: Decimal
    payment_due_date: date
    annual_fee: Decimal
    interest_rate: Decimal
    rewards_rate: Decimal
    status: CardStatus
    issued_date: date
    expiry_date: date
    last_four_digits: str
    metadata: Dict[str, Any] = field(default_factory=dict)
    created_at: datetime = field(default_factory=datetime.now)
    updated_at: datetime = field(default_factory=datetime.now)


@dataclass
class Transaction:
    """Credit card transaction data model."""
    transaction_id: str
    card_id: str
    customer_id: str
    merchant_name: str
    merchant_category: str
    amount: Decimal
    currency: str
    transaction_type: TransactionType
    status: TransactionStatus
    authorization_code: Optional[str]
    location: str
    timestamp: datetime
    settlement_date: Optional[date]
    rewards_earned: Decimal = Decimal('0')
    fraud_score: Optional[float] = None
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class AuthorizationRequest:
    """Transaction authorization request."""
    card_token: str
    amount: Decimal
    currency: str
    merchant_name: str
    merchant_category: str
    location: str
    timestamp: datetime
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class AuthorizationResponse:
    """Transaction authorization response."""
    transaction_id: str
    authorization_code: Optional[str]
    approved: bool
    decline_reason: Optional[str]
    fraud_score: float
    available_credit: Decimal
    response_time_ms: int
    timestamp: datetime


class CreditCardManager:
    """
    Core credit card management system.
    
    Handles card lifecycle, account management, and business rules.
    """
    
    def __init__(self, config: Dict[str, Any] = None):
        """Initialize credit card manager."""
        self.config = config or self._default_config()
        self.cards: Dict[str, CreditCard] = {}
        self.customers: Dict[str, Customer] = {}
        self.transactions: List[Transaction] = []
        
    def _default_config(self) -> Dict[str, Any]:
        """Get default configuration."""
        return {
            "default_credit_limit": Decimal('5000'),
            "minimum_credit_score": 650,
            "annual_fee_waiver_spend": Decimal('25000'),
            "rewards_redemption_minimum": Decimal('25'),
            "fraud_threshold": 0.7,
            "velocity_limits": {
                "daily_amount": Decimal('10000'),
                "daily_transactions": 20,
                "monthly_cash_advance": Decimal('2000')
            }
        }
    
    def create_customer(self, customer_data: Dict[str, Any]) -> Customer:
        """Create a new customer profile."""
        customer_id = str(uuid.uuid4())
        
        customer = Customer(
            customer_id=customer_id,
            first_name=customer_data['first_name'],
            last_name=customer_data['last_name'],
            email=customer_data['email'],
            phone=customer_data['phone'],
            address=customer_data['address'],
            ssn_hash=customer_data['ssn_hash'],
            date_of_birth=customer_data['date_of_birth'],
            credit_score=customer_data.get('credit_score'),
            annual_income=customer_data.get('annual_income'),
            employment_status=customer_data.get('employment_status')
        )
        
        self.customers[customer_id] = customer
        return customer
    
    def apply_for_card(self, customer_id: str, product_type: str) -> Dict[str, Any]:
        """Process credit card application."""
        customer = self.customers.get(customer_id)
        if not customer:
            return {"approved": False, "reason": "Customer not found"}
        
        # Credit decisioning logic
        decision = self._evaluate_credit_application(customer, product_type)
        
        if decision["approved"]:
            card = self._issue_card(customer, product_type, decision["credit_limit"])
            return {
                "approved": True,
                "card_id": card.card_id,
                "credit_limit": card.credit_limit,
                "annual_fee": card.annual_fee,
                "interest_rate": card.interest_rate
            }
        
        return decision
    
    def _evaluate_credit_application(self, customer: Customer, product_type: str) -> Dict[str, Any]:
        """Evaluate credit application using business rules."""
        # Basic credit scoring logic
        if not customer.credit_score or customer.credit_score < self.config["minimum_credit_score"]:
            return {"approved": False, "reason": "Insufficient credit score"}
        
        # Calculate credit limit based on income and credit score
        base_limit = self.config["default_credit_limit"]
        if customer.annual_income:
            income_factor = min(customer.annual_income / 50000, 3.0)  # Cap at 3x
            credit_score_factor = (customer.credit_score - 600) / 200  # Normalize
            credit_limit = base_limit * income_factor * credit_score_factor
            credit_limit = max(credit_limit, base_limit)  # Minimum limit
        else:
            credit_limit = base_limit
        
        return {
            "approved": True,
            "credit_limit": Decimal(str(int(credit_limit))),
            "product_type": product_type
        }
    
    def _issue_card(self, customer: Customer, product_type: str, credit_limit: Decimal) -> CreditCard:
        """Issue a new credit card."""
        card_id = str(uuid.uuid4())
        
        # Product-specific configurations
        product_config = self._get_product_config(product_type)
        
        card = CreditCard(
            card_id=card_id,
            customer_id=customer.customer_id,
            card_number_token=f"tok_{uuid.uuid4().hex[:16]}",  # Tokenized number
            card_type="Visa",  # Default to Visa
            product_name=product_type,
            credit_limit=credit_limit,
            available_credit=credit_limit,
            current_balance=Decimal('0'),
            minimum_payment=Decimal('0'),
            payment_due_date=date.today().replace(day=25),  # 25th of each month
            annual_fee=product_config["annual_fee"],
            interest_rate=product_config["interest_rate"],
            rewards_rate=product_config["rewards_rate"],
            status=CardStatus.ACTIVE,
            issued_date=date.today(),
            expiry_date=date.today().replace(year=date.today().year + 4),
            last_four_digits=f"{uuid.uuid4().hex[:4].upper()}"
        )
        
        self.cards[card_id] = card
        return card
    
    def _get_product_config(self, product_type: str) -> Dict[str, Any]:
        """Get product-specific configuration."""
        products = {
            "rewards_card": {
                "annual_fee": Decimal('95'),
                "interest_rate": Decimal('18.99'),
                "rewards_rate": Decimal('0.02')  # 2% cashback
            },
            "premium_card": {
                "annual_fee": Decimal('450'),
                "interest_rate": Decimal('16.99'),
                "rewards_rate": Decimal('0.03')  # 3% cashback
            },
            "no_fee_card": {
                "annual_fee": Decimal('0'),
                "interest_rate": Decimal('21.99'),
                "rewards_rate": Decimal('0.01')  # 1% cashback
            }
        }
        return products.get(product_type, products["no_fee_card"])
    
    def get_card_details(self, card_id: str) -> Optional[CreditCard]:
        """Get credit card details."""
        return self.cards.get(card_id)
    
    def update_card_status(self, card_id: str, new_status: CardStatus, reason: str = None) -> bool:
        """Update credit card status."""
        card = self.cards.get(card_id)
        if not card:
            return False
        
        card.status = new_status
        card.updated_at = datetime.now()
        card.metadata["status_change"] = {
            "timestamp": datetime.now().isoformat(),
            "reason": reason
        }
        
        return True
    
    def calculate_available_credit(self, card_id: str) -> Decimal:
        """Calculate available credit for a card."""
        card = self.cards.get(card_id)
        if not card:
            return Decimal('0')
        
        return card.credit_limit - card.current_balance
    
    def calculate_minimum_payment(self, card_id: str) -> Decimal:
        """Calculate minimum payment due."""
        card = self.cards.get(card_id)
        if not card:
            return Decimal('0')
        
        # Simple minimum payment calculation (2% of balance or $25, whichever is higher)
        min_payment = max(card.current_balance * Decimal('0.02'), Decimal('25'))
        return min(min_payment, card.current_balance)
    
    def get_customer_cards(self, customer_id: str) -> List[CreditCard]:
        """Get all cards for a customer."""
        return [card for card in self.cards.values() if card.customer_id == customer_id]
    
    def get_card_summary(self, card_id: str) -> Dict[str, Any]:
        """Get comprehensive card summary."""
        card = self.cards.get(card_id)
        if not card:
            return {}
        
        customer = self.customers.get(card.customer_id)
        
        return {
            "card_id": card.card_id,
            "customer_name": f"{customer.first_name} {customer.last_name}" if customer else "Unknown",
            "product_name": card.product_name,
            "card_type": card.card_type,
            "last_four": card.last_four_digits,
            "status": card.status.value,
            "credit_limit": float(card.credit_limit),
            "available_credit": float(card.available_credit),
            "current_balance": float(card.current_balance),
            "minimum_payment": float(self.calculate_minimum_payment(card_id)),
            "payment_due_date": card.payment_due_date.isoformat(),
            "annual_fee": float(card.annual_fee),
            "interest_rate": float(card.interest_rate),
            "rewards_rate": float(card.rewards_rate),
            "expiry_date": card.expiry_date.isoformat()
        }


class TransactionProcessor:
    """
    Real-time transaction processing engine.
    
    Handles authorization, fraud detection, and transaction lifecycle.
    """
    
    def __init__(self, card_manager: CreditCardManager, fraud_detector=None):
        """Initialize transaction processor."""
        self.card_manager = card_manager
        self.fraud_detector = fraud_detector
        self.authorization_rules = self._load_authorization_rules()
    
    def _load_authorization_rules(self) -> Dict[str, Any]:
        """Load transaction authorization rules."""
        return {
            "max_single_transaction": Decimal('25000'),
            "max_daily_amount": Decimal('50000'),
            "max_monthly_cash_advance": Decimal('5000'),
            "blocked_merchants": ["gambling", "adult_entertainment"],
            "international_countries": ["US", "CA", "UK", "AU"],  # Allowed countries
            "velocity_limits": {
                "transactions_per_hour": 10,
                "transactions_per_day": 50
            }
        }
    
    def authorize_transaction(self, auth_request: AuthorizationRequest) -> AuthorizationResponse:
        """Process transaction authorization request."""
        start_time = datetime.now()
        
        # Find card by token
        card = self._find_card_by_token(auth_request.card_token)
        if not card:
            return self._create_decline_response("Invalid card", start_time)
        
        # Check card status
        if card.status != CardStatus.ACTIVE:
            return self._create_decline_response("Card inactive", start_time)
        
        # Check credit limit
        if auth_request.amount > card.available_credit:
            return self._create_decline_response("Insufficient credit", start_time)
        
        # Apply authorization rules
        rule_check = self._check_authorization_rules(auth_request, card)
        if not rule_check["passed"]:
            return self._create_decline_response(rule_check["reason"], start_time)
        
        # Fraud detection
        fraud_score = 0.1  # Default low risk
        if self.fraud_detector:
            # Create transaction object for fraud analysis
            transaction = Transaction(
                transaction_id=str(uuid.uuid4()),
                card_id=card.card_id,
                customer_id=card.customer_id,
                merchant_name=auth_request.merchant_name,
                merchant_category=auth_request.merchant_category,
                amount=auth_request.amount,
                currency=auth_request.currency,
                transaction_type=TransactionType.PURCHASE,
                status=TransactionStatus.PENDING,
                location=auth_request.location,
                timestamp=auth_request.timestamp
            )
            
            # Get customer transaction history
            customer_history = self._get_customer_transaction_history(card.customer_id)
            
            # Analyze with fraud detector
            fraud_result = self.fraud_detector.analyze_transaction(
                self._convert_to_fraud_transaction(transaction),
                customer_history
            )
            fraud_score = fraud_result.score
            
            # Check fraud threshold
            if fraud_result.recommendation in ["DECLINE", "BLOCK_CARD"]:
                return self._create_decline_response("Suspected fraud", start_time, fraud_score)
        
        # Authorization approved
        transaction_id = str(uuid.uuid4())
        auth_code = f"AUTH{uuid.uuid4().hex[:8].upper()}"
        
        # Create and store transaction
        transaction = Transaction(
            transaction_id=transaction_id,
            card_id=card.card_id,
            customer_id=card.customer_id,
            merchant_name=auth_request.merchant_name,
            merchant_category=auth_request.merchant_category,
            amount=auth_request.amount,
            currency=auth_request.currency,
            transaction_type=TransactionType.PURCHASE,
            status=TransactionStatus.AUTHORIZED,
            authorization_code=auth_code,
            location=auth_request.location,
            timestamp=auth_request.timestamp,
            fraud_score=fraud_score
        )
        
        # Update card balance and available credit
        card.current_balance += auth_request.amount
        card.available_credit -= auth_request.amount
        card.updated_at = datetime.now()
        
        # Store transaction
        self.card_manager.transactions.append(transaction)
        
        # Calculate response time
        response_time = int((datetime.now() - start_time).total_seconds() * 1000)
        
        return AuthorizationResponse(
            transaction_id=transaction_id,
            authorization_code=auth_code,
            approved=True,
            decline_reason=None,
            fraud_score=fraud_score,
            available_credit=card.available_credit,
            response_time_ms=response_time,
            timestamp=datetime.now()
        )
    
    def _find_card_by_token(self, card_token: str) -> Optional[CreditCard]:
        """Find card by token."""
        for card in self.card_manager.cards.values():
            if card.card_number_token == card_token:
                return card
        return None
    
    def _check_authorization_rules(self, auth_request: AuthorizationRequest, card: CreditCard) -> Dict[str, Any]:
        """Check transaction against authorization rules."""
        # Single transaction limit
        if auth_request.amount > self.authorization_rules["max_single_transaction"]:
            return {"passed": False, "reason": "Transaction amount exceeds limit"}
        
        # Blocked merchant categories
        if auth_request.merchant_category.lower() in self.authorization_rules["blocked_merchants"]:
            return {"passed": False, "reason": "Blocked merchant category"}
        
        # Daily spending limit
        today_spending = self._calculate_daily_spending(card.card_id)
        if today_spending + auth_request.amount > self.authorization_rules["max_daily_amount"]:
            return {"passed": False, "reason": "Daily spending limit exceeded"}
        
        return {"passed": True, "reason": None}
    
    def _calculate_daily_spending(self, card_id: str) -> Decimal:
        """Calculate total spending for today."""
        today = date.today()
        daily_total = Decimal('0')
        
        for transaction in self.card_manager.transactions:
            if (transaction.card_id == card_id and 
                transaction.timestamp.date() == today and
                transaction.status == TransactionStatus.AUTHORIZED):
                daily_total += transaction.amount
        
        return daily_total
    
    def _get_customer_transaction_history(self, customer_id: str) -> List[Any]:
        """Get customer transaction history for fraud analysis."""
        # Return last 30 transactions for this customer
        customer_transactions = [
            t for t in self.card_manager.transactions 
            if t.customer_id == customer_id
        ]
        return sorted(customer_transactions, key=lambda x: x.timestamp, reverse=True)[:30]
    
    def _convert_to_fraud_transaction(self, transaction: Transaction):
        """Convert internal transaction to fraud detector format."""
        # This would convert to the fraud detector's expected format
        # For now, return a simplified version
        class FraudTransaction:
            def __init__(self, transaction):
                self.id = transaction.transaction_id
                self.customer_id = transaction.customer_id
                self.amount = transaction.amount
                self.merchant = transaction.merchant_name
                self.location = transaction.location
                self.timestamp = transaction.timestamp
                self.card_number_hash = "hash"
                self.transaction_type = transaction.transaction_type.value
        
        return FraudTransaction(transaction)
    
    def _create_decline_response(self, reason: str, start_time: datetime, fraud_score: float = 0.0) -> AuthorizationResponse:
        """Create a decline authorization response."""
        response_time = int((datetime.now() - start_time).total_seconds() * 1000)
        
        return AuthorizationResponse(
            transaction_id=str(uuid.uuid4()),
            authorization_code=None,
            approved=False,
            decline_reason=reason,
            fraud_score=fraud_score,
            available_credit=Decimal('0'),
            response_time_ms=response_time,
            timestamp=datetime.now()
        )


# Example usage and testing
if __name__ == "__main__":
    # Initialize credit card system
    card_manager = CreditCardManager()
    processor = TransactionProcessor(card_manager)
    
    # Create a customer
    customer_data = {
        "first_name": "John",
        "last_name": "Doe",
        "email": "john.doe@example.com",
        "phone": "+1-555-0123",
        "address": {
            "street": "123 Main St",
            "city": "Anytown",
            "state": "CA",
            "zip": "12345"
        },
        "ssn_hash": "hashed_ssn_value",
        "date_of_birth": date(1985, 5, 15),
        "credit_score": 750,
        "annual_income": Decimal('75000')
    }
    
    customer = card_manager.create_customer(customer_data)
    print(f"Created customer: {customer.customer_id}")
    
    # Apply for credit card
    application_result = card_manager.apply_for_card(customer.customer_id, "rewards_card")
    print(f"Application result: {application_result}")
    
    if application_result["approved"]:
        card_id = application_result["card_id"]
        card_details = card_manager.get_card_summary(card_id)
        print(f"Card details: {json.dumps(card_details, indent=2)}")
        
        # Test transaction authorization
        card = card_manager.get_card_details(card_id)
        auth_request = AuthorizationRequest(
            card_token=card.card_number_token,
            amount=Decimal('150.00'),
            currency="USD",
            merchant_name="Amazon",
            merchant_category="retail",
            location="Seattle, WA",
            timestamp=datetime.now()
        )
        
        auth_response = processor.authorize_transaction(auth_request)
        print(f"Authorization result: Approved={auth_response.approved}, "
              f"Code={auth_response.authorization_code}, "
              f"Response time={auth_response.response_time_ms}ms")